name: Create Jira Tasks from excel

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: "Path to Excel File"
        required: true
        default: 'tasks.xlsx'

jobs:
    migrate-repo:
      runs-on: ubuntu-latest

      steps:
      #Checking the Github actions repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      
