name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      task_file:
        description: 'The Excel file with Jira Task IDs'
        required: true
        default: 'tasks.xlsx'

jobs:
  fetch-jira-tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl  # Add pandas and openpyxl for Excel handling

    - name: Run the Jira Fetch Script
      env:
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
        JIRA_TASK_ID: ${{ github.event.inputs.task_file }}  # Excel file path
      run: |
        python scripts/fetch_jira_data.py

    - name: Upload JSON Outputs
      uses: actions/upload-artifact@v4
      with:
        name: jira-json-data
        path: |
          *.json  # Upload all JSON files
